### ISSUE TITLE
401 Everywhere

### ISSUE THREAD

**Issue by REtroGeekery** [proninyaroslav/OpenComicVine#1]
Every section of this app just gives me "Error: HTTP 401" I cannot get it to do anything.
![Screenshot_20230710-173758](https://github.com/proninyaroslav/OpenComicVine/assets/131400015/a4de1c3d-8646-41a0-8533-e0be9e123678)

**Comment by proninyaroslav** [comment]
HTTP 401 is Unauthorized. Did you enter a valid API key during initial setup?

**Comment by REtroGeekery** [comment]
> HTTP 401 is Unauthorized. Did you enter a valid API key during initial setup?

Yes, I signed into Comic Vine and got one. I have no idea why it's doing this.

**Comment by proninyaroslav** [comment]
You can send me your API key so I can check it out. On Telegram (same nickname as GitHub) or e-mail (proninyaroslav at gmail com)

**Comment by proninyaroslav** [comment]
I checked your key and it works. Perhaps your ISP partially blocks ComicVine? Or do you have a VPN installed?
Please try to run this URL in your browser (and don't forget to paste your key) and send me the result here:
`https://comicvine.gamespot.com/api/character/4005-1443/?api_key=PASTE YOUR API KEY HERE`

**Comment by REtroGeekery** [comment]
I get this: "This XML file does not appear to have any style information associated with it. The document tree is shown below."

"<response>
<error>OK</error>
<limit>1</limit>
<offset>0</offset>
<number_of_page_results>1</number_of_page_results>
<number_of_total_results>1</number_of_total_results>
<status_code>1</status_code>
<results>
<aliases>
Peter Parker Captain Universe Dusk Hornet Prodigy Ricochet Bombastic Bag-Man Poison Pestilence Spidey Wallcrawler Webslinger Web-Head Your Friendly Neighborhood Spider-Man Spider-Kid The Human Spider
</aliases>
<api_detail_url>
https://comicvine.gamespot.com/api/character/4005-1443/
</api_detail_url>
<birth>Oct 14, 1962</birth>
<character_enemies>
<character>
<api_detail_url>
https://comicvine.gamespot.com/api/character/4005-6819/
</api_detail_url>
<id>6819</id>
<name>8-Ball</name>
<site_detail_url>https://comicvine.gamespot.com/8-ball/4005-6819/</site_detail_url>
</character>
<character>
<api_detail_url>
https://comicvine.gamespot.com/api/character/4005-51481/
</api_detail_url>
<id>51481</id>" 
Etc.

Outside of this result, the website always works fine in my browser; it's only the app that has the 401 error. I don't have a VPN installed.

**Comment by proninyaroslav** [comment]
Yes, it works in the browser. Try to change the key in the app settings, insert it again, it's possible that a typo was made or something like that.

**Comment by REtroGeekery** [comment]
I'll give it a shot. Thanks!

**Comment by REtroGeekery** [comment]
That must have been it. I re-entered the API and it's working now. Sorry for the trouble and thanks for the assistance. Have a nice evening!
