### ISSUE TITLE
Recieving 403 error after adding API Key 

### ISSUE THREAD

**Issue by tellmeY18** [proninyaroslav/OpenComicVine#2]
![Screenshot_20240102-171504.png](https://github.com/proninyaroslav/OpenComicVine/assets/84713473/8f5db937-753a-474c-8955-f315ced509ba)

**Comment by proninyaroslav** [comment]
I'll watch it soon

**Comment by proninyaroslav** [comment]
It appears that Comic Vine has accidentally or purposefully blocked requests from the `okhttp` networking library that many Android apps use. This is weird. Changing the User Agent solves this problem, please wait for a new version.
